### PR TITLE
New fuzzy matcher algorithm

### PR DESCRIPTION
**Pull request by sassanh**
I brought it from here: https://github.com/sergei-dyshel/vim-abbrev-matcher
I think it's just much more intuitive.
It should be faster too.

### CODE REVIEW

**Comment by roxma** [comment]
> I think it's just much more intuitive.

Agreed.

> It should be faster too

I don't think so. `subprocess.Popen`  (spawning a new process) has huge overhead compared to matching in current process.And most of the cases the the amount of completion items are relative small.

In this case, I think it's better to create another matcher (`abbrev_matcher.py`) instead of overriding `fuzzy_matcher.py`.

**Comment by sassanh** [comment]
> In this case, I think it's better to create another matcher (abbrev_matcher.py) instead of overriding fuzzy_matcher.py.

sure

**Comment by roxma** [comment]
I've use cherry-pick to merge only the last commit of the PR. 

Closing.

**Comment by jsfaint** [comment]
It's weird. the new fuzzy matcher work not for me on both windows and linux with this setting

```viml
let g:cm_matcher = {'module': 'cm_matchers.abbrev_matcher'}
```

**Comment by roxma** [comment]
@jsfaint 
I forgot to mention that this module requires  the silver search, `ag` binary.

**Comment by roxma** [comment]
I would love to see someone convert it to pure python. I'm not sure how much work is required to accomplish this.

**Comment by jsfaint** [comment]
Maybe we can use this as reference https://github.com/FelikZ/ctrlp-py-matcher ?

**Pull request closed without merging**
